### ISSUE TITLE
Create OBS project

### ISSUE THREAD

**Issue by Ganza-Kagarura** [sevenxhq/scribe-scripture-editor#67]
- Create a new OBS project like the already created projects
<img width="646" alt="image" src="https://github.com/sevenxhq/scribe-scripture-editor/assets/110478373/b91ea289-3ef5-42ab-8f84-295d71435eb9">
<img width="586" alt="image" src="https://github.com/sevenxhq/scribe-scripture-editor/assets/110478373/8f159eb0-409f-42bb-b61a-d9fef4eedcf1">

**Comment by brianineza01** [comment]
Project creation was done.
