### ISSUE TITLE
Resource issues

### ISSUE THREAD

**Issue by Ganza-Kagarura** [sevenxhq/scribe-scripture-editor#82]
- [x] Replace the resource tabs with a drop down.
- [x] Simplify the rows wording and remove some unnecessary columns.
- [x] Use icons on the rows where applicable.
- [x] Downloaded resources should show on top of the list.

**Comment by Kalisa11** [comment]
Tracked by this [commit](https://github.com/sevenxhq/codex-editor/commit/dcd91ab4391480dd0345f26d689eb40886f8ed27)
